import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
    	StringBuilder result = new StringBuilder();
    	int value = 0,value1=0,value2=0;
    	for(String i : inputs) {
    		String[] str = i.split(" ");
    		//获取id
    		String id = str[0];
    		//获取数量
    		String num = str[2];
    		String name = this.itemRepository.getNameById(id);
    		int price = this.itemRepository.getPriceById(id);
    		int price1 = this.salesPromotionRepository.getPromotion2(id, price);
            int tol = Integer.parseInt(num) * price;
            value += tol;
            value2 += Integer.parseInt(num) * price1;
            result.append(name + " x " + num + " = " + tol + "元\n");
        }
        result.append("-----------------------------------\n");
        if( value>value1&&value>value2){
        	result.append("使用优惠:\n");
            value1 = this.salesPromotionRepository.getPromotion1(value);
            if (value1 <= value2 ) {
                result.append("满30减6元，省6元\n");
                result.append("-----------------------------------\n");
                result.append("总计：" + value1 + "元\n");
            } else {
                result.append("指定菜品半价(黄焖鸡，凉皮)，省13元\n");
                result.append("-----------------------------------\n");
                result.append("总计：" + value2 + "元\n");
            }
        }else{
            result.append("总计：" + value + "元\n");
        }
        result.append("===================================");
        return result.toString();
    }
}
