import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
    	//花的钱
    	int price = 0;
    	//省
    	int less = 0;
    	//第一种优惠方式
    	SalesPromotion sp1 = null;
    	//第二种优惠方式
    	SalesPromotion sp2 = null;
    	StringBuilder sb = new StringBuilder();
    	sb.append("============= 订餐明细 =============\n");
    	List<Item> item = itemRepository.findAll();
    	//优惠方式
    	List<SalesPromotion> sales = salesPromotionRepository.findAll();
    	String half="";
    	for(SalesPromotion sale:sales) {
    		if(sale.getType().equals("BUY_30_SAVE_6_YUAN")) {
    			sp1=sale;
    		}else
    			sp2=sale;
    	}
    	for(String i:inputs) {
    		String[] str = i.split(" ");
    		
    		String id = str[0];
    		String num = str[2];
    		int number = Integer.valueOf(num);
    		for(Item it:item) {
    			if(id.equals(it.getId())) {
    				if(sp2.getRelatedItems().contains(it.getId())) {
    					less+=((int)it.getPrice()/2);
    					if(half=="") {
    						half = it.getName();
    					}else {
    						half+=("，"+it.getName());
    					}
    				}
    				sb.append(it.getName()+" x "  + num + " = " + (number*(int)it.getPrice())+"元\n");
    				price+=(int)number*it.getPrice();
    				break;
    			}
    		}
    	}
    	if(price>=30||less>0) {
    		sb.append("-----------------------------------\n使用优惠:\n");
    	}
    	if(price>=30&&less<=6) {
    		less=6;
    		sb.append(sp1.getDisplayName()+"，省"+less+"元\n");
    	}
    	if(less>6) {
    		sb.append(sp2.getDisplayName()+"("+half+")");
    		sb.append("，省"+less+"元\n");
    	}
    	sb.append("-----------------------------------\n" + 
    			"总计："+(price-less)+"元\n" + 
    			"===================================");
    	
    	System.out.println(sb.toString());
        return sb.toString();
    }
}
